Test build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -204,7 +204,7 @@ jobs:
           current_version=$(grep '^version = ' pyproject.toml | cut -d '"' -f2)
           date_suffix=".dev$(date +%Y%m%d)"
           build_number=${{ github.run_number }}
-          new_version="${current_version}${date_suffix}+${build_number}"
+          new_version="${current_version}${date_suffix}.${build_number}"
           if [[ $current_version != *"$date_suffix" ]] || [[ $current_version != *"+${build_number}" ]]; then
             sed -i.bak "s/^version = \".*\"/version = \"${new_version}\"/" pyproject.toml
             rm -f pyproject.toml.bak  # Clean up backup file
@@ -586,7 +586,7 @@ jobs:
             if ! aws s3 cp "$file" "s3://${{ env.CLOUDFLARE_R2_BUCKET_NAME }}/simple/nautilus-trader/" \
               --endpoint-url=${{ secrets.CLOUDFLARE_R2_URL }} \
               --content-type "application/zip"; then
-              echo "Failed to upload $file"
+              echo "Failed to upload $file to CloudFlare R2" >&2
               exit 1
             fi
           done
@@ -629,8 +629,8 @@ jobs:
               fi
 
               # Extract the base name, platform, and version suffix
-              base=$(echo "$file" | sed -E "s/^(.+)-[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+\+[0-9]+-(.+)\.whl/\1/")
-              platform=$(echo "$file" | sed -E "s/^.+-([0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+\+[0-9]+)-(.+)\.whl/\2/")
+              base=$(echo "$file" | sed -E "s/^(.+)-[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+\.[0-9]+-(.+)\.whl/\1/")
+              platform=$(echo "$file" | sed -E "s/^.+-([0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+\.[0-9]+)-(.+)\.whl/\2/")
 
               echo "Base: $base, Platform: $platform"
 
