Test build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,7 +2,7 @@ name: build
 
 on:
   push:
-    branches: [master, develop]
+    branches: [master, develop, build]
   pull_request:
     branches: [develop]
 
@@ -96,13 +96,6 @@ jobs:
       - name: Install build dependencies
         run: python -m pip install --upgrade pip setuptools wheel pre-commit
 
-      # ta-lib Python install currently broken
-      # https://github.com/TA-Lib/ta-lib-python/issues/655
-      # - name: Install TA-Lib (Linux)
-      #   run: |
-      #     make install-talib
-      #     poetry run pip install setuptools numpy==1.26.4 ta-lib
-
       - name: Cached pre-commit
         id: cached-pre-commit
         uses: actions/cache@v4
@@ -168,9 +161,15 @@ jobs:
           fi
           make cargo-test
 
+      - name: Build and install Python wheel
+        run: |
+          poetry build --format wheel
+          poetry install --no-root --with test --all-extras
+          pip install "$(ls dist/*.whl)[all]"
+
       - name: Run tests (Linux)
         run: |
-          make pytest
+          pytest --ignore=tests/performance_tests --new-first --failed-first
           make test-examples
 
       # Run codspeed for latest python-version only
@@ -179,238 +178,238 @@ jobs:
         uses: CodSpeedHQ/action@v3
         with:
           token: ${{ secrets.CODSPEED_TOKEN }}
-          run: make test-performance
+          run: pytest tests/performance_tests --benchmark-disable-gc --codspeed
 
-  build-windows:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [windows-latest]
-        python-version: ["3.11", "3.12"]
-    defaults:
-      run:
-        shell: bash
-    name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
-    env:
-      BUILD_MODE: debug
-      RUST_BACKTRACE: 1
-      # https://github.com/Mozilla-Actions/sccache-action
-      SCCACHE_GHA_ENABLED: "true"
-      SCCACHE_CACHE_MULTIARCH: 1
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Run sccache-cache
-        uses: mozilla-actions/sccache-action@v0.0.6
-
-      - name: Set sccache-cache env vars (Windows)
-        run: |
-          echo RUSTC_WRAPPER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
-          echo CMAKE_C_COMPILER_LAUNCHER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
-          echo CMAKE_CXX_COMPILER_LAUNCHER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
-
-      - name: Free disk space (Windows)
-        run: |
-          rm -rf "/c/Program Files/dotnet"
-          rm -rf "/c/Program Files (x86)/Microsoft Visual Studio/2019"
-
-      - name: Set up Rust toolchain
-        run: |
-          rustup toolchain add --profile minimal stable --component clippy,rustfmt
-
-      - name: Set up Python environment
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Get Python version
-        run: |
-          version=$(bash scripts/python-version.sh)
-          echo "PYTHON_VERSION=$version" >> $GITHUB_ENV
-
-      - name: Get Poetry version from poetry-version
-        run: |
-          version=$(cat poetry-version)
-          echo "POETRY_VERSION=$version" >> $GITHUB_ENV
-
-      - name: Install Poetry
-        uses: snok/install-poetry@v1
-        with:
-          version: ${{ env.POETRY_VERSION }}
-
-      - name: Install build dependencies
-        run: python -m pip install --upgrade pip setuptools wheel pre-commit
-
-      - name: Cached pre-commit
-        id: cached-pre-commit
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pre-commit
-          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
-
-      - name: Cached cargo
-        id: cached-cargo
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: ${{ runner.os }}-cargo-
-
-      - name: Set poetry cache-dir
-        run: echo "POETRY_CACHE_DIR=$(poetry config cache-dir)" >> $GITHUB_ENV
-
-      - name: Cached poetry
-        id: cached-poetry
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.POETRY_CACHE_DIR }}
-          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-
-      - name: Cached test data
-        id: cached-testdata-large
-        uses: actions/cache@v4
-        with:
-          path: tests/test_data/large
-          key: ${{ runner.os }}-large-files-${{ hashFiles('tests/test_data/large/checksums.json') }}
-          restore-keys: ${{ runner.os }}-large-files-
-
-      - name: Run pre-commit
-        run: |
-          # pre-commit run --hook-stage manual gitlint-ci
-          pre-commit run --all-files
-
-      # Run tests without parallel build (avoids linker errors)
-      - name: Run tests (Windows)
-        run: |
-          poetry install --with test --all-extras
-          poetry run pytest --ignore=tests/performance_tests --new-first --failed-first
-        env:
-          PARALLEL_BUILD: false
-
-  build-macos:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [macos-latest]
-        python-version: ["3.11", "3.12"]
-    defaults:
-      run:
-        shell: bash
-    name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
-    env:
-      BUILD_MODE: debug
-      RUST_BACKTRACE: 1
-      # https://github.com/Mozilla-Actions/sccache-action
-      SCCACHE_GHA_ENABLED: "true"
-      SCCACHE_CACHE_MULTIARCH: 1
-      RUSTC_WRAPPER: "sccache"
-      CC: "sccache clang"
-      CXX: "sccache clang"
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Run sccache-cache
-        uses: mozilla-actions/sccache-action@v0.0.6
-
-      - name: Free disk space (macOS)
-        run: |
-          sudo rm -rf ~/Library/Caches/*
-          sudo rm -rf ~/Library/Developer/Xcode/DerivedData/*
-          sudo rm -rf /Library/Developer/CommandLineTools
-
-      - name: Set up Rust toolchain
-        run: |
-          rustup toolchain add --profile minimal stable --component clippy,rustfmt
-
-      - name: Set up Python environment
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Get Python version
-        run: |
-          version=$(bash scripts/python-version.sh)
-          echo "PYTHON_VERSION=$version" >> $GITHUB_ENV
-
-      - name: Get Poetry version from poetry-version
-        run: |
-          version=$(cat poetry-version)
-          echo "POETRY_VERSION=$version" >> $GITHUB_ENV
-
-      - name: Install Poetry
-        uses: snok/install-poetry@v1
-        with:
-          version: ${{ env.POETRY_VERSION }}
-
-      - name: Install build dependencies
-        run: python -m pip install --upgrade pip setuptools wheel pre-commit
-
-      - name: Cached pre-commit
-        id: cached-pre-commit
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pre-commit
-          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
-
-      - name: Cached cargo
-        id: cached-cargo
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: ${{ runner.os }}-cargo-
-
-      - name: Set poetry cache-dir
-        run: echo "POETRY_CACHE_DIR=$(poetry config cache-dir)" >> $GITHUB_ENV
-
-      - name: Cached poetry
-        id: cached-poetry
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.POETRY_CACHE_DIR }}
-          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
-
-      - name: Cached test data
-        id: cached-testdata-large
-        uses: actions/cache@v4
-        with:
-          path: tests/test_data/large
-          key: ${{ runner.os }}-large-files-${{ hashFiles('tests/test_data/large/checksums.json') }}
-          restore-keys: ${{ runner.os }}-large-files-
-
-      - name: Run pre-commit
-        run: |
-          # pre-commit run --hook-stage manual gitlint-ci
-          pre-commit run --all-files
-
-      - name: Run nautilus_core cargo tests (macOS)
-        run: |
-          if ! command -v cargo-nextest &> /dev/null
-          then
-              echo "cargo-nextest not found, installing..."
-              cargo install cargo-nextest
-          else
-              echo "cargo-nextest is already installed"
-          fi
-          make cargo-test
-
-      - name: Run tests (macOS)
-        run: |
-          make pytest
-          make test-examples
+  # build-windows:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [windows-latest]
+  #       python-version: ["3.11", "3.12"]
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
+  #   runs-on: ${{ matrix.os }}
+  #   env:
+  #     BUILD_MODE: debug
+  #     RUST_BACKTRACE: 1
+  #     # https://github.com/Mozilla-Actions/sccache-action
+  #     SCCACHE_GHA_ENABLED: "true"
+  #     SCCACHE_CACHE_MULTIARCH: 1
+  #
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Run sccache-cache
+  #       uses: mozilla-actions/sccache-action@v0.0.6
+  #
+  #     - name: Set sccache-cache env vars (Windows)
+  #       run: |
+  #         echo RUSTC_WRAPPER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
+  #         echo CMAKE_C_COMPILER_LAUNCHER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
+  #         echo CMAKE_CXX_COMPILER_LAUNCHER="${{ env.SCCACHE_PATH }}" >> $GITHUB_ENV
+  #
+  #     - name: Free disk space (Windows)
+  #       run: |
+  #         rm -rf "/c/Program Files/dotnet"
+  #         rm -rf "/c/Program Files (x86)/Microsoft Visual Studio/2019"
+  #
+  #     - name: Set up Rust toolchain
+  #       run: |
+  #         rustup toolchain add --profile minimal stable --component clippy,rustfmt
+  #
+  #     - name: Set up Python environment
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #
+  #     - name: Get Python version
+  #       run: |
+  #         version=$(bash scripts/python-version.sh)
+  #         echo "PYTHON_VERSION=$version" >> $GITHUB_ENV
+  #
+  #     - name: Get Poetry version from poetry-version
+  #       run: |
+  #         version=$(cat poetry-version)
+  #         echo "POETRY_VERSION=$version" >> $GITHUB_ENV
+  #
+  #     - name: Install Poetry
+  #       uses: snok/install-poetry@v1
+  #       with:
+  #         version: ${{ env.POETRY_VERSION }}
+  #
+  #     - name: Install build dependencies
+  #       run: python -m pip install --upgrade pip setuptools wheel pre-commit
+  #
+  #     - name: Cached pre-commit
+  #       id: cached-pre-commit
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/pre-commit
+  #         key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
+  #
+  #     - name: Cached cargo
+  #       id: cached-cargo
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           ~/.cargo/bin/
+  #           ~/.cargo/registry/index/
+  #           ~/.cargo/registry/cache/
+  #           ~/.cargo/git/db/
+  #           target/
+  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: ${{ runner.os }}-cargo-
+  #
+  #     - name: Set poetry cache-dir
+  #       run: echo "POETRY_CACHE_DIR=$(poetry config cache-dir)" >> $GITHUB_ENV
+  #
+  #     - name: Cached poetry
+  #       id: cached-poetry
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ env.POETRY_CACHE_DIR }}
+  #         key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #
+  #     - name: Cached test data
+  #       id: cached-testdata-large
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: tests/test_data/large
+  #         key: ${{ runner.os }}-large-files-${{ hashFiles('tests/test_data/large/checksums.json') }}
+  #         restore-keys: ${{ runner.os }}-large-files-
+  #
+  #     - name: Run pre-commit
+  #       run: |
+  #         # pre-commit run --hook-stage manual gitlint-ci
+  #         pre-commit run --all-files
+  #
+  #     # Run tests without parallel build (avoids linker errors)
+  #     - name: Run tests (Windows)
+  #       run: |
+  #         poetry install --with test --all-extras
+  #         poetry run pytest --ignore=tests/performance_tests --new-first --failed-first
+  #       env:
+  #         PARALLEL_BUILD: false
+  #
+  # build-macos:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [macos-latest]
+  #       python-version: ["3.11", "3.12"]
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #   name: build - Python ${{ matrix.python-version }} (${{ matrix.os }})
+  #   runs-on: ${{ matrix.os }}
+  #   env:
+  #     BUILD_MODE: debug
+  #     RUST_BACKTRACE: 1
+  #     # https://github.com/Mozilla-Actions/sccache-action
+  #     SCCACHE_GHA_ENABLED: "true"
+  #     SCCACHE_CACHE_MULTIARCH: 1
+  #     RUSTC_WRAPPER: "sccache"
+  #     CC: "sccache clang"
+  #     CXX: "sccache clang"
+  #
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #
+  #     - name: Run sccache-cache
+  #       uses: mozilla-actions/sccache-action@v0.0.6
+  #
+  #     - name: Free disk space (macOS)
+  #       run: |
+  #         sudo rm -rf ~/Library/Caches/*
+  #         sudo rm -rf ~/Library/Developer/Xcode/DerivedData/*
+  #         sudo rm -rf /Library/Developer/CommandLineTools
+  #
+  #     - name: Set up Rust toolchain
+  #       run: |
+  #         rustup toolchain add --profile minimal stable --component clippy,rustfmt
+  #
+  #     - name: Set up Python environment
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #
+  #     - name: Get Python version
+  #       run: |
+  #         version=$(bash scripts/python-version.sh)
+  #         echo "PYTHON_VERSION=$version" >> $GITHUB_ENV
+  #
+  #     - name: Get Poetry version from poetry-version
+  #       run: |
+  #         version=$(cat poetry-version)
+  #         echo "POETRY_VERSION=$version" >> $GITHUB_ENV
+  #
+  #     - name: Install Poetry
+  #       uses: snok/install-poetry@v1
+  #       with:
+  #         version: ${{ env.POETRY_VERSION }}
+  #
+  #     - name: Install build dependencies
+  #       run: python -m pip install --upgrade pip setuptools wheel pre-commit
+  #
+  #     - name: Cached pre-commit
+  #       id: cached-pre-commit
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.cache/pre-commit
+  #         key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
+  #
+  #     - name: Cached cargo
+  #       id: cached-cargo
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           ~/.cargo/bin/
+  #           ~/.cargo/registry/index/
+  #           ~/.cargo/registry/cache/
+  #           ~/.cargo/git/db/
+  #           target/
+  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: ${{ runner.os }}-cargo-
+  #
+  #     - name: Set poetry cache-dir
+  #       run: echo "POETRY_CACHE_DIR=$(poetry config cache-dir)" >> $GITHUB_ENV
+  #
+  #     - name: Cached poetry
+  #       id: cached-poetry
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ env.POETRY_CACHE_DIR }}
+  #         key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
+  #
+  #     - name: Cached test data
+  #       id: cached-testdata-large
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: tests/test_data/large
+  #         key: ${{ runner.os }}-large-files-${{ hashFiles('tests/test_data/large/checksums.json') }}
+  #         restore-keys: ${{ runner.os }}-large-files-
+  #
+  #     - name: Run pre-commit
+  #       run: |
+  #         # pre-commit run --hook-stage manual gitlint-ci
+  #         pre-commit run --all-files
+  #
+  #     - name: Run nautilus_core cargo tests (macOS)
+  #       run: |
+  #         if ! command -v cargo-nextest &> /dev/null
+  #         then
+  #             echo "cargo-nextest not found, installing..."
+  #             cargo install cargo-nextest
+  #         else
+  #             echo "cargo-nextest is already installed"
+  #         fi
+  #         make cargo-test
+  #
+  #     - name: Run tests (macOS)
+  #       run: |
+  #         make pytest
+  #         make test-examples
